name: Deploy

on:
  push:
    branches:
      - lab-4

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd /home/ubuntu/ITMO-ACS-Backend-2026-C/БР2.2/Зарецкий Юрий/labs/lab2

            git fetch origin lab-4
            git reset --hard origin/lab-4

            docker compose down

            docker compose up -d --build

            docker image prune -f